### ISSUE TITLE
CAN I PLEASE HAVE YOUR ATTENTION!!!

### ISSUE THREAD

**Issue by Usman-Click** [aungxinmoe/bloc_api#1]
Hi,
Please did you find the solution to this problem (Img below) ?
![Screenshot_20220717-144605_GitHub.jpg](https://user-images.githubusercontent.com/47116342/179401440-282d6f38-6d65-45ec-9d07-89bb59b70b7a.jpg)

**Comment by aungxinmoe** [comment]
No ,i cannot found this solution.

**Comment by Usman-Click** [comment]
okay, thanks
